### ISSUE TITLE
Binary distribution for CI

### ISSUE THREAD

**Issue by maoe** [haskell-hvr/cabal-plan#29]
I use the `make-travis-yml` to generate `.travis.yml` and I'd like to use `cabal-plan list-bin` to get the path to the final executable for deployment. Is there any plan to provide binary distribution of cabal-plan, or probably migrate this command into cabal-install?

**Comment by phadej** [comment]
- there are vague plans to provide something like `cabal-plan list-bin` into `cabal-install`, but the problem is that:
- someone need to spec the functionality: as the functionality is in `cabal-install` it's slow to change, and preferably won't change
- adding `cabal-plan` to CI is possible, you can `cabal new-install cabal-plan`,  the dependencies will be cached, so it's not a big cost time-wise.

**Comment by maoe** [comment]
Thanks for the reply.

> * there are vague plans to provide something like cabal-plan list-bin into cabal-install, but the problem is that:

Glad to hear that it's planned.

> * someone need to spec the functionality: as the functionality is in cabal-install it's slow to change, and preferably won't change

Do you think the functionalities can be incorporated into cabal-install incrementally? I only need `list-bin` for now. Proposing a spec for all the functionalities sounds like a big and potentially controversial task.

> * adding cabal-plan to CI is possible, you can cabal new-install cabal-plan, the dependencies will be cached, so it's not a big cost time-wise.

Sure. It seemed a bit inefficient to build it from source in every project that needs it but maybe it's not too bad.

**Comment by phadej** [comment]
There's .xz for linux in https://github.com/haskell-hvr/cabal-plan/releases/tag/v0.6.2.0, unfortunately I have no way to produce windows or osx binaries reliably and simply enough.
